---
title: "PCA_plot_with_ANOVA"
author: "Kevin Cunningham"
date: "2/3/2022"
output: html_document
editor_options: 
  chunk_output_type: inline
---
```{r}
library("dplyr")
library("ggplot2")
library("FactoMineR")
library("stats")
library("factoextra")
library("ggfortify")
```


```{r}
quantile_df <- read.csv("../RA_Autoantibodies_2022/all_quantile_df.csv")

quantile_df$Sample_Status <- as.factor(quantile_df$Sample_Status)


```

```{r}
negative_df <- filter(quantile_df, quantile_df$Sample_Status == 'ACPA_negative')
positive_df <- filter(quantile_df, quantile_df$Sample_Status == 'ACPA_positive')
control_df <- filter(quantile_df, quantile_df$Sample_Status == 'control')

```


```{r}
col_nums = dim(positive_df)[2]
num_features1 <- ncol(quantile_df)-2
feature_names_only <- data.frame(colnames(positive_df[,1:num_features1]))
```

Run ANOVA
```{r}
ANOVA_pvalues1 <- data.frame(matrix(data = 0, nrow = num_features1, ncol=2))
ANOVA_pvalues1[1:num_features1,1] <- feature_names_only
colnames(ANOVA_pvalues1) <- cbind("Autoantibody","Pvalue")

ANOVA_pvalues1 <- data.frame(matrix(data = 0, nrow = num_features1, ncol=2))
ANOVA_pvalues1[1:num_features1,1] <- feature_names_only
colnames(ANOVA_pvalues1) <- cbind("Autoantibody","Pvalue")

for (i in 1:num_features1) {
    one.way2 <- aov( lm(get(feature_names_only[i,1]) ~ get("Sample_Status"), quantile_df))
    #one.way2 <- aov( lm(get(feature_names_only[i,1]) ~ get("Sample_Status"), quantile_df), data = quantile_df
    p_val <- summary(one.way2)[[1]][1,5]
    ANOVA_pvalues1[i,2] <- p_val
}
ordered_anova_pvalues <- ANOVA_pvalues1[order(ANOVA_pvalues1$Pvalue),]
```

```{r}
features_less_than_0.05 <- ordered_anova_pvalues[which(ordered_anova_pvalues["Pvalue"] < 0.05),]
num_sig_features <- dim(features_less_than_0.05)[1]
```


```{r}
sig_feature_list <- features_less_than_0.05[,1]
sig_feature_df = quantile_df[,which(colnames(quantile_df) %in% sig_feature_list)]
sig_feature_df$Sample_Status <- quantile_df$Sample_Status
sig_feature_df$Case_ID <- quantile_df$Case_ID
```


```{r}

#print(sig_feature_df)
sig_feature_table <- sig_feature_df[, 1:26]
#print(sig_feature_table)
pca2 <- prcomp(sig_feature_table, scale. = F)
PCA1 <- autoplot(pca2, data = sig_feature_df, colour = 'Sample_Status', 
         frame.type = 'norm')+ scale_color_manual(values = c("gray50","brown1", "steelblue3"))+ coord_fixed()
PCA1
#pdf("../RA_Autoantibodies_2022/output/PCA.pdf")
#PCA1
#dev.off()
```




